name: build packages
on:
  push:
jobs:
  build_deb_files:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: make script exectable
        run: chmod +x build/build-deb-client.sh
      - name: run script
        run: build/build-deb-client.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: msyslog-client_${{ github.sha }}.sh
          path: ${{ github.workspace }}/msyslog-client_${{ github.sha }}.deb
          if-no-files-found: error
