name: build-packages
on: [push]

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Linux Packages
        uses: kentik/pkg@v1.0.0-rc7
        with:
          name: msyslog-client
          version: 0.0.1
          arch: x86_64
          format: deb
          package: ./client/msyslog-client-package-build.yml
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: msyslog-client
          path: msyslog-client_0.0.1-1_amd64.deb
