name: build-packages
on: push
jobs:
  build_deb:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: make script executable
        run: chmod +x ./client/build-deb.sh
      - name: run script
        run: ./client/build-deb.sh
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: msyslog-client
          path: msyslog-client_$GITHUB_SHA.deb
