name: build deb-files
on:
  push:
jobs:
  build_deb_files:
    name: Generate Debian Package
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: make script exectable
        run: chmod +x client/build-deb.sh
      - name: run script
        run: client/build-deb.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: msyslog-client*.deb
          path: ./client/*.deb
          if-no-files-found: error
