name: build packages
on:
  push:
jobs:
  build_deb_file:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: make script exectable
        run: chmod +x ${{ github.workspace }}/build/build-deb-client.sh
      - name: run script
        run: ${{ github.workspace }}/build/build-deb-client.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: msyslog-client_${{ github.sha }}.sh
          path: ${{ github.workspace }}/msyslog-client_${{ github.sha }}.deb
          if-no-files-found: error
        # install and check
      - name: install package
        run: sudo apt install --fix-broken ${{ github.workspace }}/msyslog-client_${{ github.sha }}.deb -y
      - name: enable systemd-unit
        run: sudo systemctl enable msyslog-client.service
      - name: start systemd-unit
        run: sudo systemctl status msyslog-client.service
      - name: get status of systemd-unit
        run: sudo systemctl status msyslog-client.service
      - name: check if install was successful
        run: sudo msyslog-client.sh --help
