name: Debian-Control-File-Build-Example
on:
  push:
#    branches: [ master, main ]
#  workflow_dispatch:

jobs:
  deb-control-file-build:
    name: Generate Debian Package
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v1
        # Generate Debian control File
      - name: Generate Debian control File
        uses: Nightwind-Developments/debian-control-file-builder@latest
        id: deb_control
        # Input Parameters
        with:
          # Required: Configuration File
          config-file: 'client/build-config.json'
          # Optional: deps-file
          deps-file: 'client/dependencies.txt'
          # Optional: Custom Output Directory
          # output-path: 'desired/path/to/generated/file/named/control'
          # Optional: Case Sensitive JSON Keys
          # case-sensitive-keys: 'true'

        # Upload the Generated control File as an Artifact
      - name: Upload Generated Control File
        uses: actions/upload-artifact@v2
        with:
          name: generated-control-file
          path: "${{ steps.deb_control.outputs.control_file_path }}"
          if-no-files-found: error
