name: build release
on:
  push:
#     branches: # erstmal auskomemntiert
#      - master
jobs:
  build_deb:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: make script executable
        run: chmod +x ${{ github.workspace }}/client/build.sh
      - name: run script
        run: ${{ github.workspace }}/client/build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: msyslog-client_${{ github.sha }}.deb
          path: ${{ github.workspace }}/msyslog-client_${{ github.sha }}.deb
          if-no-files-found: error

  create_release:
    needs: build_deb
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: msyslog-client_${{ github.sha }}.deb
          path: ${{ github.workspace }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/msyslog-client_${{ github.sha }}.deb
          asset_name: msyslog-client_${{ github.sha }}.deb
          asset_content_type: application/deb
